name: Test CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo "CI works"
      - with:
          github_token: ${{secrets.GH_TOKEN}}